### ISSUE TITLE
print output of command

### ISSUE THREAD

**Issue by le91688** [Zetier/lariat#19]
## Description:

When we run things with large amounts of output, such as unit tests, results written to the json field can be hard to read making it harder to troubleshoot what went wrong.

We should write output to stdout via print so that it is easier to read and troubleshoot.

## Steps to reproduce:

Run a command that generates a large amount of output.
Check the json field in the output.
Note that the output is difficult to read.

## Expected behavior:

The output should be written to stdout so that it is easier to read in CI logs and troubleshoot.

## Actual behavior:

The output is written to the json field, which is difficult to read.

## Possible solutions:

Write the output to stdout via print.

**Comment by andy-zetier** [comment]
I think this is better handled by external tools. For example, you can pipe the output of `lariat` into `jq` to achieve exactly what you want here. For example:

```console
$ lariat -f serial=FA69L0300966 -c "id" | jq -r '.FA69L0300966.output'
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid) context=u:r:shell:s0
```
