### ISSUE TITLE
Support Pushing Files and Executing Commands in a Single Job

### ISSUE THREAD

**Issue by le91688** [Zetier/lariat#21]
## Description:
Currently, Lariat only supports pushing files as a standalone job or executing a command/executable file independently. This enhancement proposes modifying the code to allow both pushing files and executing a command or executable file in the same job.

## Proposed Fix:
The suggested fix involves changing the second elif statement to an if statement. This adjustment will enable Lariat to perform file pushing, execute commands, or run an executable file sequentially in a single job.

## Code Changes:

```py
# Current Code
if args.push_files:
    device_result = process_push_files(adb_device, args.push_files, stf_device)
elif args.command:
    device_result = process_command(adb_device, args.command, stf_device)
elif args.exec_file:
    logging.info("Executing binary [%s] on device [%r]", args.exec_file, device_serial)

# Proposed Fix
if args.push_files:
    device_result = process_push_files(adb_device, args.push_files, stf_device)
if args.command:
    device_result = process_command(adb_device, args.command, stf_device)
elif args.exec_file:
    logging.info("Executing binary [%s] on device [%r]", args.exec_file, device_serial)
```

With this modification, users will be able to use the `-p` or `--push-files` flag to push files and then use the `--command` flag or `--exec-file` flag to execute commands or run an executable file, all within the same Lariat job.

## Expected Behavior:
After implementing this fix, users can run a command similar to the following example:

```sh
lariat  --push-files file.txt --command "cat /data/local/tmp/file.txt"
```

This command will push file.txt from the local machine to the remote device and then cat the pushed file on the remote device in the same job.

**Comment by random-guess** [comment]
Do you know when you'll be able to get the fixes merged in? Super useful feature being able to push and exec in a single command.

**Comment by adam-zetier** [comment]
@random-guess We have tested the MR internally and merged into master. We will be producing a 0.1.1 release soon that includes this fix.

**Comment by adam-zetier** [comment]
@random-guess, version 0.1.1 is now available. Should you encounter any problems with the new/fixed functionality, please don't hesitate to report them. We also welcome any issue tickets or pull requests for bug fixes and enhancements.
