### ISSUE TITLE
Reserve device for period of time

### ISSUE THREAD

**Issue by Twink-Polar** [Zetier/lariat#26]
Could the following scenario be achieved?

I'd like lariat to reserve a device in my stf pool, which would allow me to connect to the device via ADB over TCP. That connection would need to be held open for a period of time, allowing me to create a ADB forward tunnel and run another program on my host that talks through the established ADB tunnel to a service listening on a specific port running on the stf device. 

I need the already established ADB over TCP link as it helps me get around NATing and IP routing issues in my STF setup. 

Would this be possible?

**Comment by awm129** [comment]
A feature like this would indeed be very convenient. I personally have a bunch of custom scripts designed to work with ADB connected devices that would be very powerful to use across a full range if I could rely on lariat to setup the ADB network connection. I implemented a similar feature for another tool so I know this is possible but may take a bit of doing within lariat.

At this time we don't have any plans to add such a feature, but PRs are always welcome.

**Comment by Twink-Polar** [comment]
I'll give it a try to work something into lariat. Most likely won't be pretty but hopefully functional

**Comment by Twink-Polar** [comment]
I've just picked back up on this. Thinking about simplicity for my first attempt. I'll create new argparse for lock and unlock device. However for my requirement I'll be using the hosts ADB to establish the remote TCP tunnel to the device instead of adb_shell as I want other applications to use that connection.

**Comment by Twink-Polar** [comment]
I grossly overestimated my ability to work on this task. Far beyond my python skills.

Whilst it's still a requirement of mine, I won't be the one who implements it. 

Closing.
